### ISSUE TITLE
Transfer of NuGet package ownership

### ISSUE THREAD

**Issue by damageboy** [disruptor-net/Disruptor-net#10]
Hi Olivier,
I don't know if you've been following, but I'm getting ready to release the 2.10.1 version of disruptor, which is the last version in the 2.x series...

* Ported the java changes all the way till 2.10.1
* Re-worked some of the build process scripts
* Added more NuGet dependencies for all dependent libraries
* ported most of the DisruptorTests from the java version that were missing in the .NET port (that uncovered a few inconsistencies BTW).
* Added automatic Git information inside the .dll

I was wondering if you could add me as an owner to the NuGet package that you own:
https://www.nuget.org/packages/Disruptor/

(You need to sign in and click "manage owners", and add me, "damageboy").

Thanks!

**Comment by MendelMonteiro** [comment]
An updated nuget package has been released at https://www.nuget.org/packages/Disruptor/3.3.4-pre which includes all changes made up until the 3.3.4 version
