### ISSUE TITLE
Disruptor-Net vs BlockingCollection?

### ISSUE THREAD

**Issue by rasheedamir** [disruptor-net/Disruptor-net#13]
Hi Guys,

I was reading Olivier (accepted) answer here:
http://stackoverflow.com/questions/13350342/should-i-synchronize-access-to-disruptor-next-publish-methods

Does it still hold true? Or now Disruptor-Net is faster than BlockingCollection. And is it production ready?

Best Regards,
/Rasheed

**Comment by MendelMonteiro** [comment]
The performance tests use ConcurrentQueue as a baseline so you can run both version on your own hardware to check the relative performance.

And yes, adding to what @joliver mentioned, we also use it in production and it's performance is very good.
