### ISSUE TITLE
Too many producers with MultiThreadedLowContentionClaimStrategy caused 100% cpu

### ISSUE THREAD

**Issue by aliverman** [disruptor-net/Disruptor-net#18]
Ran into an issue when I used a small ring buffer (2048) and then had more producers than I had CPU cores. This put the machine in a state where "SerialisePublishing" would go into a spin wait state waiting for a sequence to increment. Sadly, enough of these get into this state and the machine just caps at 100% and everything goes to a 'crawl' from 1+ million per second to sub 1k per second (sometimes even in the 10's per second). I've created a small patch on the SerialisePublishing function to Thread.Yield after a certain number of iterations (10-100 iterations seems to work well) to allow another thread on that cpu core which may increment the necessary sequence to allow the spin wait to complete successfully.  It spends so much time checking for the increment that it doesn't give time for a thread to actually do the increment (or at least seems so from my testing)

On my 8 core machine, before the patch I could go 1.3 + million with 8 producers, 9 producers would put me at 1-2k and 100% cpu usage.

After patch  I can now go 1.1+ million with 16 producers with no problem (the more I add the slower it goes, but this is expected) 

Lower number of producers seem to keep the same performance characteristics as before the patch.

**Comment by samirehk** [comment]
Hi @aliverman,
I had the same problem a couple of times, it seems to happen also in the MultiThreadedClaimStrategy.
It caused my 24 core machine to use 100% cpu.

I found this post from olivier saying that you may have this problem if you have more producers than cores: https://groups.google.com/d/msg/disruptor-net/dUVSu1TGegg/c6nSCkgh-i8J

Thread.Yeld seems to be a good solution to avoid this, or perhaps use the same WaitStrategy defined for the disruptor.
I'll try this! Maybe you could make a PR.
Thanks.

**Comment by nberglund** [comment]
Hi @aliverman!!

Any chance that you could share the patch you created for the above issue?

Thanks!!

Niels

**Comment by ocoanet** [comment]
- This strategy does not exist anymore
- SerialisePublishing does not exist anymore

Please upgrade to Disruptor-net V3
