### ISSUE TITLE
Support for .NET-4.5.2?

### ISSUE THREAD

**Issue by jbaehr** [disruptor-net/Disruptor-net#23]
Are there any plans to publish the nuget with support for .NET-4.5.2? Right now it is just a matter of recompiling it against the other framework version to make disruptor usable in .NET-4.5 applications.

**Comment by MendelMonteiro** [comment]
Hi, we initially targeted .NET 4.6.1 when porting but given that we don't use any 4.6.1 specific features I am going to target 4.5 for the next release.

**Comment by MendelMonteiro** [comment]
I've created a nuget package: https://www.nuget.org/packages/Disruptor/3.3.5.1-alpha
And will promote it to a non pre-release version once it's been verified, please feel free to start using it.

**Comment by jbaehr** [comment]
Thanks a lot; will do. I'll give you feedback next week.

**Comment by BryantL** [comment]
Has the 4.5 version been verified yet?  Can it be promoted to non pre-release?

**Comment by MendelMonteiro** [comment]
It's been verified and I just released the non pre-release version.
Thanks for the reminder.
