### ISSUE TITLE
High CPU usage in wait strategies when waiting for dependent event handlers

### ISSUE THREAD

**Issue by ocoanet** [disruptor-net/Disruptor-net#25]
All the wait strategies can generate high CPU usage when waiting for dependent handlers. While it is not an issue for CPU intensive strategies like `BusySpinWaitStrategy`, I believe it is not an expected behavior for synchronization based strategies like `BlockingWaitStrategy`.

[The issue has been reported but will not be addressed in the Java version.](https://groups.google.com/forum/#!topic/lmax-disruptor/dxpl3kVuNbY)

I see a few options here:
1. Do not fix the issue in order to stay close to the Java version.
2. Add new wait strategies to address the problem, for example `BlockingWaitStrategyWithSpinWait`.
3. Add a constructor parameter to existing wait strategies, for example `WaitForDependentSequenceMode.SpinWait` (the default being `WaitForDependentSequenceMode.BusySpin`).
4. Fix the issue in existing wait strategies, but use a very aggressive wait mode to minimize the impact. By "aggressive", I mean that the .NET `SpinWait` should be not be used to avoid `Thread.Sleep(1)`.

I like option 4.

What do you think?

**Comment by MendelMonteiro** [comment]
I would like to know what the difference in CPU usage is between option 4 and the current solution when waiting for dependent event handler

**Comment by ocoanet** [comment]
There is almost no difference in CPU usage on my laptop, even if the loop is changed to:
```cs
long availableSequence;
while ((availableSequence = dependentSequence.Value) < sequence)
{
	barrier.CheckAlert();
	Thread.Sleep(0);
}
```

The difference is that now the loop doesn’t prevent other threads from being scheduled and making forward progress.

**Comment by ocoanet** [comment]
The only way to reduce the thread CPU usage in a non-busy system is to give up your time-slice with `Thread.Sleep(1)`. `Thread.Sleep(0)` will not reduce CPU usage, but will prevent starvation.

**Comment by MendelMonteiro** [comment]
I think option 4 is the best as it 

1. Doesn't increase the API surface
2. Doesn't decrease the latency of any dependent event handlers
3. Plays nicer with other threads running on the machine

The change is so small that I don't think the deviation from the java version will create a maintenance problem.

**Comment by rverdier** [comment]
I would vote in favor of option 4 too.

Considering the second point @MendelMonteiro mentioned, I think that any non obviously busy waiting strategy should not busy wait in any case. While I understand waiting for dependent handlers is kind of a special case, I don't feel like it's special enough to completely override the expected behavior of, say, a synchronisation based strategy. My guess is that most people using non-busy waiting strategies would find that behavior surprising, if not plain wrong.

Also, without thinking too much, I fail to see how such a change would negatively affect any existing usages.

**Comment by ocoanet** [comment]
The weakness of option 4 is that users will still experience 100% CPU usage with non busy waiting strategies. However, this CPU usage will not prevent other threads from being scheduled in saturated systems.

Option 3 could allow us to provide an opt-in way to use a real `SpinWait` and thus reduce CPU usage. I doubt there would be any maintenance problem because the wait strategies are small, simple and very stable.

**Comment by MendelMonteiro** [comment]
I would do option 4 and option 2 as it would be clear to the users that a different wait strategy will have different latency characteristics.

**Comment by ocoanet** [comment]
- All blocking wait strategies now use an aggressive spin wait to wait for the dependent sequence.
- A new low CPU usage wait strategy was added.
