### ISSUE TITLE
Current solution on master is not building.

### ISSUE THREAD

**Issue by JackGrinningCat** [disruptor-net/Disruptor-net#28]
Hi,

shame on me, asking for a nuget package but never had opening the solution beforehand.
Now I tried to get it, but then while building the repository it missed a version.cs.

I could not find it in the repository. Soo, removing does the deal for compiling :) 

Btw. thanks for keeping this repository up. It's a great example and in a way shows what possible.

**Comment by ocoanet** [comment]
Hi,

Thank you for reporting this issue. I am currently cleaning up the repository while converting the projects to VS2017 format. It will be fixed in a few days.

**Comment by ocoanet** [comment]
It should be fixed now!
