### ISSUE TITLE
Single and MultiProducerSequencer confusion

### ISSUE THREAD

**Issue by Kikimora** [disruptor-net/Disruptor-net#32]
I'm trying to understand how ProcessingSequenceBarrier barrier works together with MultiProducerSequencer and cannot figure something out.

Sequencer has _cursor field with is used differently in Single and MultiProducerSequencer. In SingleProducerSequencer _cursor points to last published item while in MultiProducerSequencer _cursor points to last claimed item.

When ProcessingSequenceBarrier created it receives _cursor field as cursorSequence parameter and then pass it to wait strategy. I see how this is correct with SingleProducerSequencer but I cannot understand why this works with MultiProducerSequencer. 

I wonder if there is a potential for following scenario:
1. MultiProducerSequencer.Next called and _cursor updated to say 10.
2. Then ProcessingSequenceBarrier.WaitFor 8 called.
3. WaitFor returns 10 but this sequence could be not yet published by producer.

Thanks

**Comment by ocoanet** [comment]
I admit that the usage difference of the *_cursor* field in `SingleProducerSequencer` and in `MultiProducerSequencer ` is quite confusing.

I won't get into the sequencers implementation details as it is not required : The most important points are that **this cursor is not the "available sequence" cursor** and that **no wait strategy makes the assumption that the returned value is an avaible sequence**.

All wait strategies use some kind of spin wait on the *dependentSequence* parameter to make sure that the returned sequence is available. Some strategies, e.g. `BusySpinWaitStrategy` or `SleepingWaitStrategy`, do not even use the *cursor* parameter. However the cursor value is either the available sequence, or a sequence that is going to be available very soon, so it is used in blocking strategies before starting the spin wait on *dependentSequence*.

Hope this helps.

**Comment by ocoanet** [comment]
I updated my previous message in order to provide a more accurate explanation.

Please let me know if I can close the issue or if you still have questions on the topic.

**Comment by Kikimora** [comment]
Thank you very much for explanation and for great library. I'm closing this issue.
