### ISSUE TITLE
version 3.4.0 cause 'Invalid IL code in Disruptor.Util'  on mono 5.18.0

### ISSUE THREAD

**Issue by vivid216** [disruptor-net/Disruptor-net#38]
Mono JIT compiler version 5.18.0.268
Debian 9
I run a mono xxx.exe command, and throw exception like : 

```
System.TypeInitializationException: The type initializer for 'Disruptor.Util' threw an exception. ---> System.InvalidProgramException: Invalid IL code in Disruptor.Util:ElemOffset (object[]): IL_0008: sub

  at Disruptor.Util..cctor () [0x00000] in <a2688bbefc9a4db192615b1757478ef2>:0
   --- End of inner exception stack trace ---
  at Disruptor.MultiProducerSequencer..ctor (System.Int32 bufferSize, Disruptor.IWaitStrategy waitStrategy) [0x0003b] in <a2688bbefc9a4db192615b1757478ef2>:0
```

**Comment by vivid216** [comment]
I think lots of people use Mono but not .NET Core !!
For me, I use some open source c++ interop dll in Mono and it's not support in  .NET Core

**Comment by ocoanet** [comment]
Can you update to version 3.4.1 and verify that your issue is fixed?

**Comment by mcmillab** [comment]
any update on this? I have the same issue

**Comment by vivid216** [comment]
> Can you update to version 3.4.1 and verify that your issue is fixed?

update version 3.4.1,  both  windows and unix with mono 5.18 are execution well,  the issue can be closed,  thanks a lot !
