### ISSUE TITLE
IEventHandler<T> OnEvent System.MethodAccessException:  implicit implementation interface

### ISSUE THREAD

**Issue by vivid216** [disruptor-net/Disruptor-net#40]
if implicit implementation interface IEventHandler<T> , Disruptor.BatchEventProcessor`5.ProcessEvents() throw a System.MethodAccessException
if explicit implementation  IEventHandler<T>  and it's fine.
is StructProxy got something wrong ?

` void IEventHandler<LogEvent>.OnEvent(LogEvent data, long sequence, bool endOfBatch)`

**Comment by ocoanet** [comment]
Hello. The generated proxy method is indeed not valid for handlers with an explicit interface implementation.
I will fix this by disabling struct proxies in this situation.

**Comment by ocoanet** [comment]
Can you update to version 3.4.2 and verify that your issue is fixed?

**Comment by vivid216** [comment]
download & build the lastest code and the bug has been solved !  thanks @ocoanet
