### ISSUE TITLE
BatchEventProcessor is not updating Sequence at correct point

### ISSUE THREAD

**Issue by Grayhaam** [disruptor-net/Disruptor-net#42]
The BatchEventProcessor.ProcessEvents() method isn't updating the sequence until all the events in the batch have been processed. This is blocking other consumers/producers from processing.
The blocked processes should be allowed to continue up to the event just processed within the batch or they will be spinning needlessly.
I have the fix for it but I do not have access to push a branch.

**Comment by ocoanet** [comment]
The current behaviour is expected. You can work around it if you need to, see [this issue](https://github.com/LMAX-Exchange/disruptor/issues/255).

**Comment by Grayhaam** [comment]
Okay, thanks.
