### ISSUE TITLE
add Task and async  support for 'OnEvent' and 'Publish'

### ISSUE THREAD

**Issue by RockNHawk** [disruptor-net/Disruptor-net#43]
Disruptor is a great project with advanced technology. Thank you for bringing Disruptor to the .NET world.

The `async` and `await` signal-based wake-up mechanisms can significantly increase throughput.

I think if bring the `async` to the disruptor, it can avoid the CPU overhead of `Blocking Strategy` and `Yield Strategy` while waiting for new events to arrive, could you tell me is that true?

**Comment by MendelMonteiro** [comment]
Do you have an example of which API you change to expose as async?

Note that the `BlockingWaitStrategy` should not generate much CPU overhead as it uses a `Monitor` to signal the sleeping consumer thread. Have you seen excessive CPU usage with the `BlockingWaitStrategy` and if so, what is your configuration?

**Comment by RockNHawk** [comment]
I think we need an `IAsyncEventHandler`, such like this:

    public interface IAsyncEventHandler<in T>
    {
        Task OnEventAsync(T data, long sequence, bool endOfBatch);
    }


I just worry about it, `async` & `await` use a state machine, It should be less expensive than the Monitor lock, but this is all guessing, we need a test.

**Comment by RockNHawk** [comment]
And `RingBuffer.Publish` also need a async version `RingBuffer.PublishAsync`, the PublishAsync just await the AsyncEventHandler's Task complete.

**Comment by jed1978** [comment]
> And `RingBuffer.Publish` also need a async version `RingBuffer.PublishAsync`, the`PublishAsync` just await the AsyncEventHandler's Task complete.

In my understanding and experience, RingBuffer.PublishAsync is not needed.
You use publish method to publish the event to RingBuffer till no available slot, and other EventHandlers read the event data and process it till no new event coming . 

They already in async mode,  so if you experienced block or wait or something like that, check your event handler logic first.

**Comment by RockNHawk** [comment]
@jed1978 Yeah, I know `Publish` and IEventHandler.OnEvent is a async login and in different Thread.

I means, perhaps using .NET's Task with the async await mechanism (based on the state machine) to implement thread wakeups and notifications will consume less CPU than Monitior or other semaphores.

I know `Publish` is async and it only wait if RingBuffer is full, so the `PublishAsync` is also only make an actual `await` when RingBuffer is full too, the only different is use Monitor/Yield/Thread.Sleep(0) to implement  the wait or use `async-await`'s state machine to implement the wait, this cause different CPU useage.

and the IAsyncEventHandler.OnEventAsync is just add for it is convenient for developers to call other async methods.

    public interface IAsyncEventHandler<in T>
    {
        Task OnEventAsync(T data, long sequence, bool endOfBatch);
    }

   public class MyAsyncEventHandler<Event>:IAsyncEventHandler<Event>
   {
        public Task OnEventAsync(T data, long sequence, bool endOfBatch){
            var ret =  await xxx.InNewThreadProcessAsync(data.Xxx);
            if(ret!=null){
                await xx.Method2Async(ret);
            }
        }
    }

    await ringBuffer.PublishAsync(seq);

**Comment by MendelMonteiro** [comment]
You really don't wait to call `async` methods inside your event handler because you will effectively be putting the current `Event` into another queue somewhere (e.g. IOCompletionQueue).  Whilst the event is in this other queue the event handler thread will not be able to progress to the next event and any newly published event will just get added to the ring buffer.

You could have the same behaviour by simply using a blocking call in the event handler.

> I means, perhaps using .NET's Task with the async await mechanism (based on the state machine) to implement thread wakeups and notifications will consume less CPU than Monitior or semaphores.

Do you have any data to back this up?  I think the same underlying windows synchronisation primitives will be used in both cases.

**Comment by MendelMonteiro** [comment]
@RockNHawk?

**Comment by RockNHawk** [comment]
@MendelMonteiro Okay, thank you !

> Do you have any data to back this up? I think the same underlying windows synchronisation primitives will be used in both cases.

I have no data to back this, I still need some tests, async-await uses thread scheduling, when await ends the thread to continue execution, it may not be the original thread, which is why you can not do await call in a `lock(obj){ ... }` block, see https://asherman.io/projects/csharp-async-reentrant-locks.html
So this is very different from the Monitor mechanism.
Because I am not particularly sure whether this is really good for performance improvement, so I also want to listen to other people's views first, but ultimately need the actual data to determine....

**Comment by MendelMonteiro** [comment]
In terms of performance, using kernel synchronisations primitves is not going to be as performant as the more aggressive wait strategies that are available with the Disruptor.  You can run the performance benchmarks yourself to observe the latency that is possible.

**Comment by RockNHawk** [comment]
Okay, thank you!
Thank you again for port the .NET version of Disruptor!
