### ISSUE TITLE
Strong Naming the Disruptor Assembly?

### ISSUE THREAD

**Issue by jbaehr** [disruptor-net/Disruptor-net#47]
Hi,

We want to reference Disruptor from strong-named assemblies. This requires Disruptor to have a strong name, too. Up to now we create a strong-named version our-self, using something like this
```
ildasm Disruptor.dll /out:Disruptor.il
ilasm Disruptor.il /dll /key=path\to\SomeKey.snk
```
which is cumbersome and needs to be redone on every new version.

Do you mind signing the official Disruptor dlls on nuget.org right away, as part of your build?

Further reading: https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named

**Comment by ocoanet** [comment]
Hello.

I agree that it would be better to use a strong-name for the Disruptor assembly.

However, adding a strong-name to an assembly is a breaking change. It would be a little unfortunate to increase the major version number for this reason only but I do not see any option.

I will clearly consider that for the next release.

**Comment by ocoanet** [comment]
The Disruptor assemblies will be signed starting from the [4.0.0-beta](https://www.nuget.org/packages/Disruptor/4.0.0-beta).
