### ISSUE TITLE
EventHandlerGroup<T>.And(EventHandlerGroup<T> eventHandlerGroup) usage

### ISSUE THREAD

**Issue by Grayhaam** [disruptor-net/Disruptor-net#52]
Can you explain how I use the And() method on the EventHandlerGroup<T> class? The only method I can see to create an EventHandlerGroup object without already having one is on the disruptor class. I am trying to use it to be able to have two separate WorkerPools in the same consumer group.

Would the following achieve it?
```
var someHandlers = disruptor.HandleEventsWithWorkerPool(SomeWorkHandlers);
disruptor.HandleEventsWithWorkerPool(filterMessageWorkHandlers).And(someHandlers);
```

**Comment by ocoanet** [comment]
Hello.

```cs
// | Producer | -> | WorkerPool1 | -> | WorkerPool2 | ->
disruptor.HandleEventsWithWorkerPool(workerPool1)
         .ThenHandleEventsWithWorkerPool(workerPool2);

//                 | WorkerPool1 |
// | Producer | -> |             |
//                 | WorkerPool2 |
disruptor.HandleEventsWithWorkerPool(workerPool1);
disruptor.HandleEventsWithWorkerPool(workerPool2);

//                 | WorkerPool1 |
// | Producer | -> |             | -> Handler
//                 | WorkerPool2 |
var group1 = disruptor.HandleEventsWithWorkerPool(workerPool1);
var group2 = disruptor.HandleEventsWithWorkerPool(workerPool2);
group1.And(group2).Then(handler);
```

I hope this helps.

**Comment by Grayhaam** [comment]
Hi Oliver,

Many thanks for those examples, very helpful. Can I confirm that the following example would therefore also work?


//                               | WorkerPool1 |
// | Producer | -> | -> Handler  | -> Handler
//                               | WorkerPool2 |
var handler1 = disruptor.HandleEventsWith(Handler);

var group1 = handler1.ThenHandleEventsWithWorkerPool(workerPool1);
var group2 = handler1.ThenHandleEventsWithWorkerPool(workerPool2);
handler1.Then(group1).And(group2);

Thanks,

Graham

Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by ocoanet** [comment]
If your design is:
- Step1: Handler
- Step2: WorkerPool1 and WorkerPool2 (concurrently)

Then you can simply specify:
```cs
var step1 = disruptor.HandleEventsWith(handler);
step1.ThenHandleEventsWithWorkerPool(workerPool1);
step1.ThenHandleEventsWithWorkerPool(workerPool2);
```

**Comment by ocoanet** [comment]
```cs
var handler1 = disruptor.HandleEventsWith(Handler);

var group1 = handler1.ThenHandleEventsWithWorkerPool(workerPool1);
var group2 = handler1.ThenHandleEventsWithWorkerPool(workerPool2);
handler1.Then(group1).And(group2);
```
This is incorrect:
- `And` should be used to create logical handler groups. A handler group can then be used to create a sequence of event processors. A `And` should be followed by a `Then`: `h1.And(h2).Then(h3)`.
- `Then` generates event processors. The parameter must be a handler, it cannot be another handler group.

I have the feeling I should improve the documentation on this topic 🙂.
