### ISSUE TITLE
Long-running EventHandler causes high CPU consumption

### ISSUE THREAD

**Issue by et1975** [disruptor-net/Disruptor-net#53]
This is probably outside of the expected use of Disruptor, but I'm wondering if there's a way I could solve this - blocking an event handler for a few minutes results in `BlockingWaitStrategy` waisting a lot of cycles. The handler on its own uses no more than 2% of one core, but running in the disruptor - 100% of a core.

I've tried other strategies, including a phased strategy with the fallback to seconds-long sleep and it doesn't help.

**Comment by MendelMonteiro** [comment]
You can use the `BlockingSpinWaitWaitStrategy`: https://github.com/disruptor-net/Disruptor-net/blob/master/src/Disruptor/BlockingSpinWaitWaitStrategy.cs

The addition of this wait strategy was discussed in [this issue](https://github.com/disruptor-net/Disruptor-net/issues/25).

**Comment by ocoanet** [comment]
There is one well known high CPU usage issue: when you have a multi-stage Disruptor and your first handler is blocking.

Can you confirm that this is your scenario? Does the CPU usage come from the next event handler waiting to processing the events?

In such a situation, @MendelMonteiro answer should do the trick. I tried to explain this in the [wiki](https://github.com/disruptor-net/Disruptor-net/wiki/Wait-Strategies) but it might not be clear enough.

**Comment by et1975** [comment]
I don't think that's my scenario: I use disruptor queues as mailboxes for actors - one actor does post to another's queue, but I'm not chaining the handlers.

**Comment by ocoanet** [comment]
Is your ring buffer full? The high CPU usage could be generated by a producer trying a acquire an available sequence number.

**Comment by et1975** [comment]
Something's wrong on my side - created a barebone sample with just 2 actors and a long sleep - no CPU spikes.
Sorry, closing.
