### ISSUE TITLE
DynamiclyAddHandler can't work

### ISSUE THREAD

**Issue by kamikyo** [disruptor-net/Disruptor-net#56]
Disruptor-net/src/Disruptor.Samples/DynamiclyAddHandler.cs can't work
ps: I replaced Start with WaitUntilStarted(TimeSpan.Zero)

**Comment by ocoanet** [comment]
The code sample is not supposed to be run as is: there is no point in removing an handler that was just added. I added a `Thread.Sleep` to clarify that the removal is supposed to happen later.
