### ISSUE TITLE
Is it safe to use Disruptor with System.IO.Pipelines without extra allocations?

### ISSUE THREAD

**Issue by robertmircea** [disruptor-net/Disruptor-net#60]
I have a TCP server application with binary protocol packets. The server uses System.IO.Pipeline to receive messages from the socket, frame them (length prefix) and later decode them in objects. I am looking to improve the performance by offloading the decoding of the message bytes with disruptor and later process the message. Is it safe to publish ReadOnlySequence<byte> resulted from message framing into Disruptor? I am looking for a way to avoid extra allocations (e.g. do not copy or transfer the sequence into a new byte buffer every time)

The code looks similar to this:

```
          var reader = socketConnection.Input;
            try
            {
                while (!cancellationToken.IsCancellationRequested)
                {
                    var readResult = await reader.ReadAsync(cancellationToken).ConfigureAwait(false);
                    var buffer = readResult.Buffer;
                    if (readResult.IsCanceled)
                        break;
                    
                    if (buffer.IsEmpty && readResult.IsCompleted) 
                        break;

                    var consumed = buffer.Start;
                    var examined = buffer.End;

                    if (FixedSizePipeProtocolFramer.TryParseLengthPrefixedPacket(in buffer, packetMaxSize, ref consumed, ref examined, out ReadOnlySequence<byte> payload)) {
                        //do something with payload like publishing into disruptor's ring buffer. Is it safe?
                    }
                    if (readResult.IsCompleted)
                        break;

                    reader.AdvanceTo(consumed, examined);
                }
            }
[...]
```

**Comment by ocoanet** [comment]
I do not know much about about System.IO.Pipeline, so I may not be the best person to answer this question, but here are my two cents.

I suppose that here `payload` references the buffer bytes. I also suppose that you are expected to process the buffer relatively fast and to release it. So you do not own the buffer and you cannot enqueue it in the ring buffer.

I only see two options:

1. Copy the payload to a ring buffer event

```cs
using (var scope = ringBuffer.PublishEvent())
{
    var e = scope.Event();
    payload.CopyTo(e.Buffer);
}
```

```cs
public class Event
{
    public byte[] Buffer { get; }
}
```

2. Decode the payload into a ring buffer event

```cs
using (var scope = ringBuffer.PublishEvent())
{
    var e = scope.Event();
    decoder.Decode(payload, e.Message);
}
```

```cs
public class Event
{
    public Message Message { get; }
}
```

I suspect that decoding is slower than or equivalent to the copy. But if you need to decode the data at some point, the option 2 does not increase your end-to-end latency. I would probably not choose option 1 unless the decoding is very slow and cannot be performed in the buffer processing thread.  

If you decide to go with option 1, it might be cleaner to use a value or unmanaged ring buffer in order to copy the data into the ring buffer itself, instead of using an event that references another buffer.

If you decide to go with option 2, you might have a "slow publisher" issue, depending on the number of other publishers. I can explain this point if needed.

**Comment by MendelMonteiro** [comment]
You generally want to create your disruptors when the process starts and keep it alive for the life of the process. Especially if you want to avoid allocating.
If you have variable length data and fixed length buffers you will probably need to use an array pool to avoid allocations before passing the data to the Disruptor to decode. But that would basically add an extra copy to your critical path. If as @ocoanet suggests your decoding is as fast as copying bytes it might not be a good choice.

**Comment by ocoanet** [comment]
>In case of option 1, if the message has variable length, what would be a good strategy to avoid additional bytes buffer allocations or at least minimise them?

Do you have a known limit on the message length (the length of your largest message) or do you need to support arbitrary large messages? In the later case you might need to split your messages, for example:
```cs
var payloadLength = payload.Length;
var eventCount = 1 + payloadLength / Event.Capacity;

// Acquire eventCount contiguous events and publish them together.
// The event handler will need to use BufferCount to identify split messages.
using (var scope = ringBuffer.PublishEvents(eventCount))
{
    for (var (index, sliceStart) = (0, 0); index < eventCount; index++, sliceStart += Event.Capacity)
    {
        var e = scope.Event(index);
        e.BufferCount = eventCount;
        e.BufferIndex = index;

        var sliceLength = Math.Min(Event.Capacity, payloadLength - sliceStart)
        payload.Slice(sliceStart, sliceLength).CopyTo(e.Buffer);
    }
}
```

```cs
public class Event
{
    public const int Capacity = TODO;
    public int BufferCount { get; set; }
    public int BufferIndex { get; set; }
    public byte[] Buffer { get; }
}
```

**Comment by ocoanet** [comment]
As a rule of thumb you should try to limit the number of disruptors in you application and to avoid creating them dynamically. In your case, I would probably use a configurable number of disruptors and bind the TCP sessions to disruptor instances (~ sharding).

Using a single disruptor with a WorkerPool might also be an interesting good approach. But using multiple disruptors will reduce the contention on the publishing side. In addition, the WorkerPool will not support the message splitting technique that I described earlier.

**Comment by ocoanet** [comment]
You might get a slightly better memory layout using a value disruptor. For example:

```cs
var payloadLength = payload.Length;
var eventCount = 1 + payloadLength / Event.Capacity;

// Acquire eventCount contiguous events and publish them together.
// The event handler will need to use BufferCount to identify split messages.
using (var scope = ringBuffer.PublishEvents(eventCount))
{
    for (var (index, sliceStart) = (0, 0); index < eventCount; index++, sliceStart += Event.Capacity)
    {
        ref var e = ref scope.Event(index);
        e.BufferCount = eventCount;
        e.BufferIndex = index;

        var sliceLength = Math.Min(Event.Capacity, payloadLength - sliceStart)
        var payloadSlice = payload.Slice(sliceStart, sliceLength);
        var buffer = MemoryMarshal.CreateSpan(ref e.BufferStart, sliceLength);
        payloadSlice.CopyTo(buffer);
    }
}
```

```cs
[StructLayout(LayoutKind.Explicit, Size=Size)]
public struct Event
{
    public const int Size = 1024; // TODO
    public const int Capacity = Size - 8;
    [FieldOffset(0)]
    public int BufferCount;
    [FieldOffset(4)]
    public int BufferIndex;
    [FieldOffset(8)]
    public byte BufferStart;
}
```

Also you could take the red pill and write into multiple events as if they were one event, but I would not try this unless you expect large messages to be very common (and you could measure a significant performance improvement).

**Comment by robertmircea** [comment]
Thank you for the pointers, very helpful. Probably you should add a new article to the wiki explaining this usage. One more question: In case that in the event handler's `OnEvent`  I need to execute an async method, is there anything smarter/efficient to do rather than `Wait` for the task to complete? I don't have any chained event handlers and I don't need to process any results after execution, maybe just log the error but for this I used `disruptor.SetDefaultExceptionHandler(new DisruptorExceptionHandler<SocketReceivedPacketEvent>(Logger));`

Currently I have the following:

```
    public void OnEvent(SocketReceivedPacketEvent data, long sequence, bool endOfBatch)
    {
        protocolHandler.HandlePacket(data.DecodedPacket).Wait();
    }
```

**Comment by ocoanet** [comment]
There are many options for dealing with async code in the Disruptor. I tried to describe some of them in a [recent blog post](https://medium.com/@ocoanet/disruptor-and-tasks-why-you-cannot-have-async-event-handlers-ef815088eb4c). You also could try the new async handler which is available in the [V5](https://github.com/disruptor-net/Disruptor-net/releases/tag/5.0.0-rc1).

For your use case:
- Waiting in the handler is fine.
- You should probably explicitly wait with a timeout unless you are absolutely sure that the underlying async API already has a timeout.
- It is often more efficient to wait at the end of the batch, depending on how you async API is implemented (see the note on batching in the blog post). In any case, try to see if you can improve your throughput using the disruptor batches.
- You must be sure that the event handler can process the events fast enough. Even with a large ring buffer size, you might get into full ring buffer and backpressure issues.
- It might be a good idea to explicitly [release your events early](https://github.com/disruptor-net/Disruptor-net/wiki/Event-Handlers#making-events-available-to-next-event-handlers).

**Comment by ocoanet** [comment]
@robertmircea I will let you close the issue if you do not have any further questions. Also, if you have time, I would be interested in a some feedback regarding your use case or simply the Disruptor API and documentation (you can PM me on twitter).

**Comment by robertmircea** [comment]
I am evaluating if disruptor would bring any performance (i am interested in latency reduction) benefit in a sms gateway application which is used in production in our telecom company. Currently the sms gateway implements smsc interface using a specific industry binary protocol which under the hood uses system.io.pipeline to process TCP socket communication. Disruptor was inserted in network messaging part to see if I can temporarely decouple network packet framing and deserialization from actual packet processing logic at application level.

What I believe is missing from disruptor documentation is actual examples of real world usage (where does it fit as place in app framework stacks, examples of where it can be used, real examples documented of usage in async scenarios, how disruptor should be instantiated multiple times in a process or be used in pooled mode, comparison with .NET channels). The most interesting topics for me are about usage of disruptor for efficient tcp server/client packet processing using minimal or no allocation.

**Comment by MendelMonteiro** [comment]
There are many resources available (blogs and presentations) that detail the LMAX architecture and how the disruptor can fit into an application.
A starting point would be https://martinfowler.com/articles/lmax.html.
