### ISSUE TITLE
Read method without locals

### ISSUE THREAD

**Issue by buybackoff** [disruptor-net/Disruptor-net#65]
I've compared the Read method with `Unsafe` implementation I used to use before. It's faster than `Unsafe`, but I found cases in my code where perf dropped by 9%. Without locals the perf improved as expected by 5% vs original or 14% vs the version with locals.

``` 
   [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Read<T>(object array, int index)
        where T : class
    {
        // IL.DeclareLocals(false, typeof(byte).MakeByRefType());
        //
        // Ldarg(nameof(array));
        // Stloc_0(); // convert the object pointer to a byref
        // Ldloc_0(); // load the object pointer as a byref

        Ldarga(nameof(array));
        Ldind_Ref();
```

Fir the Disruptor benchmark the performance is identical. My theory is that it's basically the same stuff, but with too many IL locals JIT sometimes gives up to optimize, or something from this genre. This particular benchmark was always very sensitive to locals even in the inlined method it does not directly go through.

**Comment by ltrzesniewski** [comment]
I'm surprised this doesn't thow an `InvalidProgramException`. This changes a `&` type on the stack to an `O` type, and arithmethic on those is not supported:

![image](https://user-images.githubusercontent.com/7913492/155107200-f543db1d-b2ab-4a92-871d-3680dff28d45.png)

**Comment by buybackoff** [comment]
Brr, this throughput numbers mean very little with different batching on a noisy machine. Need more precise measurement and some extra work 😄

**Comment by ltrzesniewski** [comment]
> It's weird - the distinction between object reference and managed pointer is of little value. Object reference is a manager pointer to a method table. The math should work, only the verifier could complain.

Yes, I know about that, but the spec is pretty explicit about it: 

> Managed pointers are _not_ interchangeable with object references.

Though the current code is storing an `O` value in a `&` local, and I couldn't find a mention in ECMA-335 which would allow that in the first place...

**Comment by ltrzesniewski** [comment]
> However, we could change ArrayDataOffset to calculate the offset not from the method table, but from the first data byte.

You should calculate this using an array instead of a regular object (`T[]` instead of `RawData<T>`) as you should not assume the CLR uses the same layout for objects and for arrays.

**Comment by buybackoff** [comment]
@ltrzesniewski `Unsafe.As<RawData<T>>(array).Data` points right after the method table. What we do now is pointing to the method table. In array case, the `.Data` points to its Length slot. Do you know about differences in the method table size? Or other stuff that could be placed before `.Data` on different implementations?

**Comment by ltrzesniewski** [comment]
> In array case, the `.Data` points to its Length slot.

Exactly. Don't we want the offset between the first element and the method table, thus skipping the length slot?

**Comment by buybackoff** [comment]
> Don't we want the offset between the first element and the method table, thus skipping the length slot?

We can [calculate it](https://github.com/Spreads/Spreads/blob/309d63049859bec2ca3a3895f1599f5a6fb3fd79/src/Spreads.Core/TypeHelper.cs#L128), but we cannot make it a JIT constant in easy way.

So now we have on x64:  `FirstOffset = MT_Ptr + ArrayDataOffset = MT_Ptr +  8 (MT_PtrSize) [.Data is here] +  4 (uint Length) + 4 (Padding) `. What I propose is to just point past MT_Ptr and use existing knowledge about different stuff after .Data on different implementations.

**Comment by ltrzesniewski** [comment]
> we cannot make it a JIT constant in easy way.

Oh, ok, I see 👍

> use existing knowledge about different stuff after .Data on different implementations.

But that's exactly what `ArrayDataOffset` does... how would you like to change that more precisely?

**Comment by buybackoff** [comment]
> But that's exactly what ArrayDataOffset does... how would you like to change that more precisely?

By using Unsafe and not `Ldind.Ref` and still avoiding locals.

**Comment by ltrzesniewski** [comment]
Oh, ok, sorry, I misunderstood what you were saying earlier :+1:

**Comment by buybackoff** [comment]
https://github.com/dotnet/runtime/discussions/65793

**Comment by buybackoff** [comment]
The current implementation is optimal for x-plat. 

For .NET Core it works even with simple `Ldarg(nameof(array)) + offset`, and I think it should works like that and the O and & separation is artificial both conceptually and implementation-wise. But for this kind of things there is the linked discussion.

**Comment by ltrzesniewski** [comment]
I suppose the reason for having both `O` and `&` types is performance: GC scans should be faster for `O` types, as the GC can assume the value is a pointer to a method table. This gets more complicated for `&` values, which can point to anywhere inside an object.

But I'm very interested in the answer to your linked question. 🙂
