### ISSUE TITLE
Is there a way to ensure backpressure on producers and not overwrite?

### ISSUE THREAD

**Issue by rcocks-hl** [disruptor-net/Disruptor-net#67]
I am using version 4.0.0 of Disruptor.

I have a single producer which is producing random numbers.

Right now I have a single handler which I want to consume the randomly generated numbers.

My payload object is 

        public class RandomValue
        {
            public long value;
            public long counter;
        }

Where `value` is the random number and `counter` is a counter in the producer (which with one producer is always the same as the sequence number).

When I set up the disruptor and set it going, my consumer class is being fed very high sequence numbers.

Even making the ring buffer size a really small number, it's still getting a really high sequence number.

Also even with a small ring buffer size, the producer is not blocked on the `Next` call as I understand it should be.

My waitStrategy is `BlockingWaitStrategy` so I thought the producer call to `Next` was supposed to block when the ring is full, so how am I generating so many values in the producer before the consumer is consuming them?

Instead there's no back pressure at all on the producer.

I have tried to consume with both `HandleEventsWithWorkerPool` instead of `HandleEventsWith` and both have the same behaviour.

**Comment by ocoanet** [comment]
Hello.

Please note that the wait strategy configures how a given event handler (consumer) is waiting for new events. It is not related to the backpressure mechanism. In `BlockingWaitStrategy`, blocking simply indicates that the event handler will be blocked (by `Monitor.Wait`) when waiting for new events.

The backpressure is almost hardcoded in the disruptor in the `Next` methods, and you can only avoid it by calling `TryNext`. But `TryNext` will fail when the ring buffer is full, so you cannot override unprocessed events.

If you do not experience any backpressure in your tests, it probably means that your consumer is very fast, maybe as fast as the producer, so you cannot fill the ring buffer even with a small capacity. You could probably add a `Sleep` in your consumer to verify that the backpressure is effective.

Here is a very naive sample that demonstrate backpressure:
```cs
public static void Main(string[] args)
{
    var disruptor = new Disruptor<Event>(() => new Event(), 4);

    disruptor.HandleEventsWith(new Handler());
    disruptor.Start();

    PublishEvents();

    Thread.Sleep(4000);

    PublishEvents();

    Thread.Sleep(4000);

    disruptor.Shutdown();

    void PublishEvents()
    {
        for (var i = 0; i < 10; i++)
        {
            Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss.fff} PUB before acquire");

            var sequence = disruptor.RingBuffer.Next();
            try
            {
                Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss.fff} PUB after acquire {sequence}");

                // Configure event
                disruptor.RingBuffer[sequence].Id = Guid.NewGuid();
            }
            finally
            {
                disruptor.RingBuffer.Publish(sequence);

                Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss.fff} PUB after publish {sequence}");
            }
        }
    }
}

private class Handler : IEventHandler<Event>
{
    public void OnEvent(Event data, long sequence, bool endOfBatch)
    {
        Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss.fff} SUB begin {sequence}");

        Thread.Sleep(1000);

        Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss.fff} SUB end {sequence}");
    }
}

private class Event
{
    public Guid Id { get; set; }
}
```

**Comment by ocoanet** [comment]
First, I suppose that you want to use `IEventHandler`, which is the disruptor standard consumer interface, and not `IWorkHandler`, which is used to register pools of consumers.

Then, I think that your issue is quite clear: **you should setup your disruptor before publishing events**.

The backpressure is generated by the consumers. In fact, every consumer is a source of backpressure: events must be processed by all consumers before they can be reused for new publications. But there is no backpressure in an empty disruptor.

If you start publishing the events in an empty disruptor (i.e.: a ring buffer without consumers), then you can publish as many event as you want, and you will end up overriding events.

You should not think if the disruptor as a bounded queue, which can get filled. The disruptor is a data-structure that connects and synchronizes producers and consumers. 

You can experiment using this code:
```cs
public static void Main()
{
    var disruptor = new Disruptor<Event>(() => new Event(), 4);

    // Uncomment this line to register the handler, thus generate backpressure.
    // disruptor.HandleEventsWith(new Handler());

    for (var i = 0; i < 10; i++)
    {
        if (!disruptor.RingBuffer.TryNext(out var sequence))
        {
            Console.WriteLine($"I could not publish event {i} :(");
            continue;
        }

        Console.WriteLine($"I could publish event {i}!");
        disruptor.RingBuffer.Publish(sequence);
    }

    Console.WriteLine("Press enter to exit...");
    Console.ReadLine();
}

private class Handler : IEventHandler<Event>
{
    public void OnEvent(Event data, long sequence, bool endOfBatch)
    {
    }
}

private class Event
{
}
```

Registering the handler is enough to generate backpressure, you do not need to start the disruptor.

**Comment by ocoanet** [comment]
I will definitely update the documentation to make this behavior more explicit.

Starting your consumers on a filled buffer seems to be a strange requirement. However, it is quite easy to achieve. First, add your handler(s) to the disruptor, then start publishing your events, and only after, start the disruptor. You could also simply use a `ManualResetEventSlim` to prevent your handlers from processing the events, but it might negatively impact your handler performance, so I would prefer the publish-before-start strategy.

**Comment by ocoanet** [comment]
I rewrote the getting-started page of the Disruptor ([here](https://gist.github.com/ocoanet/c936a354410fbd4957a174c92f7daf28)).

Could you review it before I publish it to make sure it is helpful?

I included an explicit note about publishing before adding event handlers.

**Comment by rverdier** [comment]
It means the fields are mutable (they are set within the public `Initialize` method in the sample code). The ring buffer events themwelves cannot be overwriten ([the RingBuffer indexer has no setter](https://github.com/disruptor-net/Disruptor-net/blob/master/src/Disruptor/RingBuffer%601.cs#L147)).
