### ISSUE TITLE
Is it safe/possible to use ByRefLike value types as events for  ValueDisruptor?

### ISSUE THREAD

**Issue by kooshan** [disruptor-net/Disruptor-net#68]
I'm trying to avoid buffer allocations for my downstream ring buffer, which would in turn invoke a handler which encodes/serializes messages to clients. Messages are comprised of an array of entities at this point in application. So in contrast to my other ring buffers which also used `ValueDisruptor` and carry around single value type entities, I have a fixed length array of entities at this stage. I'm trying to switch all arrays with Span<T> constructs and allocate the memory with `stackalloc` on the ring itself. This also enforces that the Disruptor event which embraces the Span<T> should also be a ByRefLike type. But I'm not sure if this could work since whether me dynamically allocating with `stackalloc ` collides with `PublishEvent()`/`scope.Event()` functionality and also that ByRefLike types are forced to always be handled on stack and many more restriction which frankly I do not have any idea if it would be respected though out inner workings of disruptor.

```
public ref struct SomeEvent                         // this is now ref struct
{
      ...
      public Span<SomeEntity> Items;          // change from SomeEntity[] Items
}

public struct SomeEntity
{
      ...
}
```
I'm trying to do this:
```
public void Produce(ref Span<SomEntity> messages)
{
      using var scope = disruptor.PublishEvent();
      ref var @event = ref scope.Event();
      @event.Items = stackalloc SampleEntity[fixedCount];
      messages.CopyTo(@event.Payload.Items);
}
```
Instead of something like this with normal structs:
```
public void Produce(ref Span<SomEntity> messages)
{
      using var scope = disruptor.PublishEvent();
      ref var @event = ref scope.Event();
      @event.Items = ArrayPool<SomeEntity>.Shared.Rent(fixedCount);
      messages.CopyTo(@event.Payload.Items);
}
```

**Comment by MendelMonteiro** [comment]
The ring buffer is used to pass data between two threads therefore you will not be able to pass a stack-allocated array between the two threads.

If you have a list of entities that need to be processed you have two choices.  

1. You can either rent an array as you do in your second example and then publish the event to ring buffer with the array, making sure to release the array once the consumer(s) have finished processing them.

2. The other choice you have is to publish one event for each entity.  There is a slightly higher synchronisation cost to doing this but the batching mechanism in the Disruptor reduces this cost considerably.

Keep in mind that the ring buffer is essentially an array shared by the producing and consuming threads so does it make sense to put other arrays within each element of the ring buffer array?

**Comment by kooshan** [comment]
Thank you very much. I ended up following option 2. It is worth mentioning a third option which I found to be quite interesting
[https://github.com/disruptor-net/Disruptor-net/issues/60#issuecomment-1020110153](https://github.com/disruptor-net/Disruptor-net/issues/60#issuecomment-1020110153)
