### ISSUE TITLE
.NET 6 support

### ISSUE THREAD

**Issue by dkaip** [disruptor-net/Disruptor-net#69]
Will you please consider upgrading to .NET 6 compatibility.  You use RuntimeHelpers.OffsetToStringData which has been deprecated and is unavailable in .NET 6.

**Comment by ltrzesniewski** [comment]
This works just fine for us with .NET 6. `RuntimeHelpers.OffsetToStringData` is deprecated but still available.

Can you describe your issue more specifically?

**Comment by dkaip** [comment]
Wow, thank you for your response.

FYI:
Fedora 5.19.8-200.fc36.x86_64
$ dotnet --version
6.0.108

Here is/are the errors:

$ dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
/home/dkaip/git/disruptor-net/src/Disruptor/Util/Util.cs(123,19): error CS0618: 'RuntimeHelpers.OffsetToStringData' is obsolete: 'OffsetToStringData has been deprecated. Use string.GetPinnableReference() instead.' [/home/dkaip/git/disruptor-net/src/Disruptor/Disruptor.csproj]
/home/dkaip/git/disruptor-net/src/Disruptor/Util/Util.cs(124,19): error CS0618: 'RuntimeHelpers.OffsetToStringData' is obsolete: 'OffsetToStringData has been deprecated. Use string.GetPinnableReference() instead.' [/home/dkaip/git/disruptor-net/src/Disruptor/Disruptor.csproj]

Perhaps I shot myself in the foot...my changes
##################################################################
$ git diff Disruptor/Disruptor.csproj
diff --git a/src/Disruptor/Disruptor.csproj b/src/Disruptor/Disruptor.csproj
index c34508f..a34c603 100644
--- a/src/Disruptor/Disruptor.csproj
+++ b/src/Disruptor/Disruptor.csproj
@@ -1,7 +1,7 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFrameworks>net452;netstandard2.0</TargetFrameworks>
+    <TargetFrameworks>net6.0</TargetFrameworks>
     <GenerateDocumentationFile>true</GenerateDocumentationFile>
     <IsPackable>true</IsPackable>
     <PackageId>Disruptor</PackageId>
@@ -10,8 +10,8 @@
 
   <ItemGroup>
     <PackageReference Include="System.Reflection.Emit" Version="4.7.0" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
-    <PackageReference Include="Fody" Version="6.2.4" PrivateAssets="all" />
-    <PackageReference Include="InlineIL.Fody" Version="1.5.0" PrivateAssets="all" />
+    <PackageReference Include="Fody" Version="6.6.3" PrivateAssets="all" />
+    <PackageReference Include="InlineIL.Fody" Version="1.7.2" PrivateAssets="all" />
   </ItemGroup>
 
 </Project>
##################################################################
$ git diff Disruptor.Benchmarks/Disruptor.Benchmarks.csproj
diff --git a/src/Disruptor.Benchmarks/Disruptor.Benchmarks.csproj b/src/Disruptor.Benchmarks/Disruptor.Benchmarks.csproj
index 46d1aec..0d1c3bb 100644
--- a/src/Disruptor.Benchmarks/Disruptor.Benchmarks.csproj
+++ b/src/Disruptor.Benchmarks/Disruptor.Benchmarks.csproj
@@ -1,7 +1,7 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFrameworks>net48;net5.0</TargetFrameworks>
+    <TargetFrameworks>net6.0</TargetFrameworks>
     <OutputType>exe</OutputType>
   </PropertyGroup>
 
@@ -10,9 +10,9 @@
   </ItemGroup>
 
   <ItemGroup>
-    <PackageReference Include="BenchmarkDotNet" Version="0.12.1" />
-    <PackageReference Include="Fody" Version="6.2.4" PrivateAssets="all" />
-    <PackageReference Include="InlineIL.Fody" Version="1.5.0" PrivateAssets="all" />
+    <PackageReference Include="BenchmarkDotNet" Version="0.13.2" />
+    <PackageReference Include="Fody" Version="6.6.3" PrivateAssets="all" />
+    <PackageReference Include="InlineIL.Fody" Version="1.7.2" PrivateAssets="all" />
     <PackageReference Include="ObjectLayoutInspector" Version="0.1.2" />
   </ItemGroup>
 
@@ -20,4 +20,4 @@
     <None Remove="BenchmarkDotNet.Artifacts\**" />
   </ItemGroup>
 
-</Project>
\ No newline at end of file
+</Project>
##################################################################
$ git diff Disruptor.HeapWalker/Disruptor.HeapWalker.csproj
diff --git a/src/Disruptor.HeapWalker/Disruptor.HeapWalker.csproj b/src/Disruptor.HeapWalker/Disruptor.HeapWalker.csproj
index af7d1fe..9fdd236 100644
--- a/src/Disruptor.HeapWalker/Disruptor.HeapWalker.csproj
+++ b/src/Disruptor.HeapWalker/Disruptor.HeapWalker.csproj
@@ -1,7 +1,7 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFramework>net48</TargetFramework>
+    <TargetFramework>net6.0</TargetFramework>
     <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
     <OutputType>exe</OutputType>
   </PropertyGroup>
@@ -11,7 +11,7 @@
   </ItemGroup>
 
   <ItemGroup>
-    <PackageReference Include="Microsoft.Diagnostics.Runtime" Version="0.9.180305.1"/>
+    <PackageReference Include="Microsoft.Diagnostics.Runtime" Version="2.2.332302"/>
   </ItemGroup>
 
-</Project>
\ No newline at end of file
+</Project>
##################################################################
$ git diff Disruptor.PerfTests/Disruptor.PerfTests.csproj
diff --git a/src/Disruptor.PerfTests/Disruptor.PerfTests.csproj b/src/Disruptor.PerfTests/Disruptor.PerfTests.csproj
index 3c3ce7d..77e1a68 100644
--- a/src/Disruptor.PerfTests/Disruptor.PerfTests.csproj
+++ b/src/Disruptor.PerfTests/Disruptor.PerfTests.csproj
@@ -1,7 +1,7 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFrameworks>net48;net5.0</TargetFrameworks>
+    <TargetFrameworks>net6.0</TargetFrameworks>
     <OutputType>exe</OutputType>
     <SignAssembly>false</SignAssembly>
   </PropertyGroup>
@@ -11,9 +11,9 @@
   </ItemGroup>
 
   <ItemGroup>
-    <PackageReference Include="BenchmarkDotNet" Version="0.12.1" />
+    <PackageReference Include="BenchmarkDotNet" Version="0.13.2" />
     <PackageReference Include="HdrHistogram" Version="2.5.0" />
-    <PackageReference Include="System.Threading.Channels" Version="4.7.1" />
+    <PackageReference Include="System.Threading.Channels" Version="6.0.0" />
   </ItemGroup>
 
-</Project>
\ No newline at end of file
+</Project>
##################################################################
$ git diff Disruptor.Samples/Disruptor.Samples.csproj
diff --git a/src/Disruptor.Samples/Disruptor.Samples.csproj b/src/Disruptor.Samples/Disruptor.Samples.csproj
index 655908a..51ebd28 100644
--- a/src/Disruptor.Samples/Disruptor.Samples.csproj
+++ b/src/Disruptor.Samples/Disruptor.Samples.csproj
@@ -1,7 +1,7 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFramework>net5.0</TargetFramework>
+    <TargetFramework>net6.0</TargetFramework>
     <OutputType>exe</OutputType>
     <StartupObject>Disruptor.Samples.Wiki.GettingStarted.SampleProgram</StartupObject>
   </PropertyGroup>
@@ -10,4 +10,4 @@
     <ProjectReference Include="..\Disruptor\Disruptor.csproj" />
   </ItemGroup>
 
-</Project>
\ No newline at end of file
+</Project>
##################################################################
$ git diff Disruptor.Tests/Disruptor.Tests.csproj
diff --git a/src/Disruptor.Tests/Disruptor.Tests.csproj b/src/Disruptor.Tests/Disruptor.Tests.csproj
index e817003..5a786ae 100644
--- a/src/Disruptor.Tests/Disruptor.Tests.csproj
+++ b/src/Disruptor.Tests/Disruptor.Tests.csproj
@@ -1,7 +1,7 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFrameworks>net48;net5.0</TargetFrameworks>
+    <TargetFrameworks>net6.0</TargetFrameworks>
   </PropertyGroup>
 
   <ItemGroup>
@@ -9,11 +9,11 @@
   </ItemGroup>
 
   <ItemGroup>
-    <PackageReference Include="Fody" Version="6.2.4" PrivateAssets="all" />
-    <PackageReference Include="InlineIL.Fody" Version="1.5.0" PrivateAssets="all" />
-    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
-    <PackageReference Include="NUnit" Version="3.12.0" />
-    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
+    <PackageReference Include="Fody" Version="6.6.3" PrivateAssets="all" />
+    <PackageReference Include="InlineIL.Fody" Version="1.7.2" PrivateAssets="all" />
+    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.1" />
+    <PackageReference Include="NUnit" Version="3.13.0" />
+    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
   </ItemGroup>
 
-</Project>
\ No newline at end of file
+</Project>
##################################################################

**Comment by dkaip** [comment]
Sorry, when I submitted the comment it reformatted the git diff's.  If you need it I can try and drag and drop a formatted file.

**Comment by MendelMonteiro** [comment]
You don't need to target .NET 6.0 for the Disruptor to be used as a library in a .NET 6.0 app so you should not have to change the targeted framework versions at all.

**Comment by dkaip** [comment]
Okay Thank you.
When I try and do the same command (dotnet test) it says I need to load a lot of .NET stuff that I do not appear to have loaded.

I was hoping to not have to have a bunch of legacy stuff loaded and just start my development efforts from .NET 6 and above.

Is there a repository like Maven Central for C# where I can get trusted compatible binaries and just get on with life?

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: Cannot open assembly '/usr/lib64/dotnet/sdk/6.0.108/Extensions/..//TestHost/testhost.net48.x86.exe': No such file or directory.
. Please check the diagnostic logs for more information.

Test Run Aborted.
Test run for /home/dkaip/git/disruptor-net/src/Disruptor.Tests/bin/Debug/net5.0/Disruptor.Tests.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 17.0.0+68bd10d3aee862a9fbb0bac8b3d474bc323024f3
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: You must install or update .NET to run this application.
App: /home/dkaip/.nuget/packages/microsoft.testplatform.testhost/16.6.1/lib/netcoreapp2.1/testhost.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '5.0.0' (x64)
.NET location: /usr/lib64/dotnet/
The following frameworks were found:
  6.0.8 at [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=fedora.36-x64
. Please check the diagnostic logs for more information.

Test Run Aborted.
  Disruptor.PerfTests -> /home/dkaip/git/disruptor-net/src/Disruptor.PerfTests/bin/Debug/net5.0/Disruptor.PerfTests.dll

**Comment by MendelMonteiro** [comment]
Try adding this to the csproj files if you do not want to downlyad / install the 5.0 framework:
`<RollForward>Major</RollForward>`.  See: https://learn.microsoft.com/en-us/dotnet/core/versions/selection#control-roll-forward-behavior

By the way, the equivalent to Maven Central would be Nuget and you can get all the required packages from there by running `dotnet restore`.

**Comment by ocoanet** [comment]
> Is there a repository like Maven Central for C# where I can get trusted compatible binaries and just get on with life?

Yes, you should reference the Disruptor using the [nuget package](https://www.nuget.org/packages/Disruptor) instead of compiling the project manually.

You can simply add a package reference to your csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Disruptor" Version="4.0.0" />
  </ItemGroup>

</Project>
```

**Comment by ltrzesniewski** [comment]
@ocoanet the code may need a `#pragma warning disable CS0618` around `OffsetToStringData` though.

Or we could calcuate the value from `GetPinnableReference`, but that would require special-casing with `#if`/`#else`

**Comment by ocoanet** [comment]
You are right, I will create an issue to fix this.

**Comment by ocoanet** [comment]
I just noticed the `#pragma` is [already here](https://github.com/disruptor-net/Disruptor-net/blob/master/src/Disruptor/Util/InternalUtil.cs#L40)...

**Comment by ltrzesniewski** [comment]
Oh, right. Looks like @dkaip didn't compile the latest version (Util.cs was renamed in 7f865e3343b1bc7446c386b34298c746788f11ac)
