### ISSUE TITLE
PerfTests doesn't compile when Nuget Disruptor is referenced

### ISSUE THREAD

**Issue by dbevernage** [disruptor-net/Disruptor-net#7]
When you reference the Nuget "Disruptor-net" (containing atomic, Disruptor, Disruptor.Scheduler), directly from the Disruptor.PerfTests project, it doesn't compile anymore.

The compilation error happens in class ValueAdditionEventHandler has a private field of type "System.Threading.Volatile.PaddedLong".
Oddly enough, this is a type in assembly "System.Threading.Tasks.Dataflow" which is referenced correctly and remains untouched when adding the "Disruptor-net" Nuget.

Main question: in what way is the source in GitHub different from the sources used to build the Nuget package?

**Comment by MendelMonteiro** [comment]
No longer relevant in current code base
