### ISSUE TITLE
Buffer getting full

### ISSUE THREAD

**Issue by rbotafg** [disruptor-net/Disruptor-net#70]
I'm trying to use IBatchEventHandler.
I"ve implemented the OnBatch(EventBatch<BookEvent> messages, long sequence)
It basicaly executes a foreach loop:

foreach(var message in messages.AsEnumerable())
{
   // do something with the message
}

But it seems that the buffer never gets cleared and after a while, the publisher blocks waiting for the consumer and it seems like the consumer is not consuming, although there is the foreach that is consuming data.  Am I missing something to remove the elements from the ringBuffer?

**Comment by ocoanet** [comment]
I cannot see anything wrong with your simple foreach loop. `AsEnumerable` is not required but it should not cause any issue.
However, multiple tests in the codebase indicate that basic usage of IBatchEventHandler should work as expected.

Can you provide additional context to help reproduce the problem? A simple runnable program would be ideal.

You can start with the following example and update it to match your usage:

```cs
    public static void Main()
    {
        var disruptor = new Disruptor<Event>(() => new Event(), 4096);
        disruptor.HandleEventsWith(new Handler());
        disruptor.Start();

        foreach (var index in Enumerable.Range(0, 100_000))
        {
            using var scope = disruptor.PublishEvent();
            var message = scope.Event();
            message.Id = index;
            message.Value = index + 0.1;
        }

        disruptor.Shutdown();

        Console.WriteLine("Press enter to exit");
        Console.ReadLine();
    }

    public class Event
    {
        public int Id { get; set; }
        public double Value { get; set; }
    }

    public class Handler : IBatchEventHandler<Event>
    {
        public void OnBatch(EventBatch<Event> batch, long sequence)
        {
            foreach (var message in batch.AsEnumerable())
            {
                Console.WriteLine($"Id: {message.Id}, Value: {message.Value}");
            }

            Console.WriteLine($"BatchSize: {batch.Length}");
        }
    }
```

**Comment by rbotafg** [comment]
Thanks for the reply.  I think I found the problem and it was my mistake.  In certain condition, inside the foreach I  started another thread that did add things to the ringBuffer.  I guess this got the ringBuffer confused.  I fixed it and now only start the new thread outside of the foreach.

**Comment by ocoanet** [comment]
Ok. Please note that publishing events to the ring buffer in your event handler (inside or outside the for loop) is quite dangerous. You can create a deadlock if the ring buffer gets full.
