### ISSUE TITLE
Batch rewind

### ISSUE THREAD

**Issue by rbotafg** [disruptor-net/Disruptor-net#71]
When going through messages in a batch, if certain conditions are met, I have to break out of the processing and wait for the right conditions to continue.  But I only find out that the specific condition is met after reading an element of the ringBuffer and seeing that it meets the condition.  This element, should be returned to the ringBuffer for latter processing.  I don't need to do a full rewind on the batch, just the last message.  Is this possible?

    void ProcessMessage(EventBatch<Event> messages, long sequence)
    {
        for (var i = 0; i < messages.Length; i++)
        {
          [process message[i];]

          if (messages[i].condition()) {
          {
              [return message[i] to the buffer - will be processed next time ProcessMessage is called]
              break;
         }
    }

**Comment by MendelMonteiro** [comment]
The batch rewinding has not been implemented in the .NET version of the Disruptor and there are no immeidate plans to do so.

If we were to implement it we would probably try to stay closeish to the java implementation [which is documented here](https://github.com/LMAX-Exchange/disruptor/blob/e00a7baaec4528da732be847a5c5bada65438216/src/docs/asciidoc/en/user-guide/40_batch_rewind_use_case.adoc).

Note that in the java implementation the batch would be rewound to the start of the batch and not just ignoring certain messages in the batch.  What you are trying to do seems custom enough that you might need to do it in the event handler code.  You could for example simply store the data contained in the messages that meet your conditon in a collection that you process on the next `ProcessMesage()` call.

**Comment by ocoanet** [comment]
@rbotafg 

`OnEvent` is invoked for every event, as soon as the event is published and the event handler is available to process the event (i.e.: the handler processed previously published events).

So "returning an event to the ring buffer" does not really make sense, because the event would be reprocessed right away, and if you really wanted to reprocess it right away, you could do so synchronously in the event handler.

It is not clear why you want to wait before processing specific events. But you can probably store these events in a local list (a field in your handler) and process them later. If you do so, it might be interesting to use a timeout wait strategy to make sure "discarded" messages are eventually processed.

@MendelMonteiro There is no plan to implement the batch rewind feature of the Java implementation. Batch handlers make this feature useless.

**Comment by rbotafg** [comment]
I'm trying to implement an incremental book for a crypto currency  in an exchange, but I'm not being able to do it properly.  According to the documentation, I subscribe to incremental updates - I want those updates to be stored in the ringBuffer. Then I should get a snaphot.  When I get the snapshot I want to publish all the incremental updates so that they can upgrade the snapshot.

I have a mehtod: ProcessIncrementalUpdates, that receives updates (websocket) from the Exchange.  This method tries to add data to the ringBuffer - 

     ProcessIncrementalUpdate(.....)
     {    
         sequence = _ringBuffer.next()
         var data = ringBuffer[sequence]
         ....
        if (_waitingSnapshot)          
              return                                      // Keep adding to the ringBuffer until we receive the snapshot

        publish(......);
   }

The publish method should publish a batch with all the data that was added to the ringBuffer.

Then there is

     ExecuteIncrementalUpdate(EventBatch<BookEvent> messages, long sequence)
     {
         foreach(var message in messages.AsEnumberable()) {
            if (message.valid()) {  // incremental update is really the next update
                [update the book]
           }
           else  {                        // we probably lost some messages and incremental update is not valid
               [request new snapshot]
              break;                  // do not remove the elements in the ringBuffer (they might be used after new snapshot)
           }      
    }

The problem is the publish method.  I tried PublishEvents(size), but didn't receive that data on ExecuteIncremental.  Doing
ringBuffer.Publish(lo, hi) works while we don't reach the end of the ringBuffer, when we wrap around the end, then data does not arrive properly in ExecuteIncremental.

Any help is appreciated.

**Comment by ocoanet** [comment]
To be honest I do not fully understand you design but I will try to give a few advises.

1. You should publish events after a call to `RingBuffer.Next()`. The [reference pattern](https://github.com/disruptor-net/Disruptor-net/wiki/Publication-Options) uses a finally block to ensure claimed sequence numbers are always published.
You usage of next / publish might seem to work in a single-threaded setup, but it is very dangerous and should be avoided.

2. If you need to accumulate messages before processing, you should probable either accumulate them in the publisher side (wait until your specific condition is met before publishing events) or in the consumer side (adds a copy of the messages in a queue in your handler and process them when your specific condition is met). Right now I get the impression that your solution is a mix of the two options. I would probably choose the consumer side option because it is more disruptorish.

3. Accumulating messages in a queue is probably not the best option. You might be using the Disruptor to avoid allocations, and copying messages to local collections generate allocations or require additional object pooling. Also, the extra copy might impact your performances. However book events can often be merged (conflated), so you might be able to accumulate "pending" events by merging them in a single event.

4. If you absolutely need to accumulate pending messages inside the ring buffer and wait before processing them, I can imagine a design that would work using wait handles and two event handlers. I can explain it if you do not see any other solution.

I hope this will help.

**Comment by rbotafg** [comment]
There might be better designs for what I need to do.  My design tries to follow what the exchange is sending me.  

The exchange sends lots of incremental updates.  Updates have a sequencial number, so let's say that the exchange has sent updates (1001, 1045).  It then sends a book shnapshot, let's say that the sequencial number of the shapshot is 1033.  So, to this snapshot I'll have to apply updates from 1034 to 1045.

My design tries to follow this pattern.  It accumulates in the producer updates (1001, 1045).  When the snapshot arrives, the producer publishes (1001, 1045).  The consumer gets all the updates.  From 1001 to 1033 it throws them out, from 1034 to 1045, it applies the updates.  Exchange keeps sending updates, which are published as soon as they arrive and used by the consumer.  So, let's say we received updates (1046, 1066) and then (1070, 2000).  Our book sequencial number is now 1045, so we can continue applying update from (1046, 1066), but then when we get 1070, we cannot apply it since we should apply 1067.  So, we need to request a new book snapshot.

1. I do push to the RingBuffer by doing a RingBuffer.Next, but I cannot immediately publish it, since the consumer has no place to apply this update yet (there is no book snapshot).  So, I need to accumulate it.
2. I'm accumulating only on the publisher, as I do not want to generate garbage;
3. You are right.  I do not want to accumulate on a queue. This was my design before trying to use RingBuffer;
4. It seems that this is the only option... but if you envision a better design, I'd love to hear it.

Thanks

**Comment by rbotafg** [comment]
Any comments?

**Comment by rbotafg** [comment]
It seems that Disruptor might actually not be flexible enough for my use case.  Another problem with the exchange, is that it is not guarantee that the incremental updates will be sent in order, so, I also need the ringBuffer to be sorted.  I tried to implement it, but for some rason when I publish the ringBuffer, it actually never gets published.  

So, here is the code I've implemented... I know that this is not the way to use Disruptor, but I couldn't think of another way:

```
    protected long AddSortedRingBuffer(BookDataRecord book, long seqNum, long prevSeqNum, long exchangeTimestamp, long receiveTime)
    {
        if (!_ringBuffer.TryNext(out long index))
        {
            //Console.WriteLine($"***************** {book.ExchangeName} - {index}");
            return -1;
        }

        int j = (int)index;
        int i = 1;
        do
        {
            if (prevSeqNum > _ringBuffer[j - 1].PrevSeqNum)
            {
                break;
            }

            var data = _ringBuffer[j];
            data.BookRecord = _ringBuffer[j - 1].BookRecord;
            data.SeqNum = _ringBuffer[j - 1].SeqNum;
            data.PrevSeqNum = _ringBuffer[j - 1].PrevSeqNum;
            data.ExchangeTimestamp = _ringBuffer[j - 1].ExchangeTimestamp;
            data.ReceiveTime = _ringBuffer[j - 1].ReceiveTime;
            j--;
            i++;
        } while (i <= _bufferSize);

        InsertRingBuffer(j, book, seqNum, prevSeqNum, exchangeTimestamp, receiveTime);
        _bufferSize++;
        
        return index;
    }
```
```
    protected virtual void ProcessIncrementalUpdate(BookDataRecord book, long seqNum, long prevSeqNum, long exchangeTimestamp,
        long receiveTime)
    {
        long index = AddSortedRingBuffer(book, seqNum, prevSeqNum, exchangeTimestamp, receiveTime);

        if (_waitingSnapshot)
        {
            return;
        }

        if (index == -1)
        {
            if (_bufferSize == 0)
            {
                // Try to force a Publish to get to the consumer.  Without this, there is a deadlock because the 
               // consumer never gets to consume anything.  With this, It eventually wakes up.  
                Console.Write("Publish (0, 0) ");
                _ringBuffer.Publish(0, 0);
                return;
            }

            Console.Write($"+({BufferCapacity - _bufferSize}, {BufferCapacity - 1}, {_bufferSize} )");
            _ringBuffer.Publish(BufferCapacity - _bufferSize, BufferCapacity - 1);
            _bufferSize = 0;
            return;
        }

        // Need to keep the buffer sorted, so only publish after we have 20 elements in the buffer. Publish 10 and leave the
        // other 10 to keep sorted
        if (_bufferSize > 20)
        {
            var sendSize = _bufferSize / 2;
            var lo = index - _bufferSize + 1;
            Console.Write($"-({lo}, {index - sendSize}, {sendSize} )");
            _ringBuffer.Publish(lo, sendSize);
            _bufferSize -= sendSize;
        }
    }
```

**Comment by rbotafg** [comment]
Disruptor might not be flexible enough for my use case.  To make things worse, I need to keep the ringBuffer sorted, as incremental updates might not come in in order.  Here is my effort to try to make this work - it doesn't, altough it looks like it almost works.

```
    protected long AddSortedRingBuffer(BookDataRecord book, long seqNum, long prevSeqNum, long exchangeTimestamp, long receiveTime)
    {
        // if buffer is full, just drop the new incremental update
        if (!_ringBuffer.TryNext(out long index))
        {
            return -1;
        }

        // keep the buffer sorted by prevSeqNum
        int j = (int)index;
        int i = 1;
        do
        {
            if (prevSeqNum > _ringBuffer[j - 1].PrevSeqNum)
            {
                break;
            }

            var data = _ringBuffer[j];
            data.BookRecord = _ringBuffer[j - 1].BookRecord;
            data.SeqNum = _ringBuffer[j - 1].SeqNum;
            data.PrevSeqNum = _ringBuffer[j - 1].PrevSeqNum;
            data.ExchangeTimestamp = _ringBuffer[j - 1].ExchangeTimestamp;
            data.ReceiveTime = _ringBuffer[j - 1].ReceiveTime;
            j--;
            i++;
        } while (i <= _bufferSize);

       // add the new data in the proper place in the ringBuffer
        var data = _ringBuffer[index];
        data.BookRecord = book;
        data.SeqNum = seqNum;
        data.PrevSeqNum = prevSeqNum;
        data.ExchangeTimestamp = exchangeTimestamp;
        data.ReceiveTime = receiveTime;
        _bufferSize++;

        return index;
    }
```

```
    protected virtual void ProcessIncrementalUpdate(BookDataRecord book, long seqNum, long prevSeqNum, long exchangeTimestamp,
        long receiveTime)
    {
        long index = AddSortedRingBuffer(book, seqNum, prevSeqNum, exchangeTimestamp, receiveTime);

        // if we are already waiting for a snapshot, then we just add incremental updates to the buffer
        if (_waitingSnapshot)
        {
            return;
        }

        // if the ringBuffer is full, publish the whole ringBuffer
        if (index == -1)
        {

            // This is an effort to get the ringBuffer published.  If this is not done, it deadlocks as the consumer never gets to
            // wake up.  With a bunch o fake publish, the consumer eventually wakes up and consumes the buffer
            if (_bufferSize == 0)
            {
                _ringBuffer.Publish(0, 0);
                return;
            }

            _ringBuffer.Publish(BufferCapacity - _bufferSize, BufferCapacity - 1);
            _bufferSize = 0;
            return;
        }

        // Only publish when the buffer has at least 20 elements, so that we can keep some elements sorted.  Only publish 10
        // elements and let the rest be sorted
        if (_bufferSize > 20)
        {
            var sendSize = _bufferSize / 2;
            var lo = index - _bufferSize + 1;
            _ringBuffer.Publish(lo, sendSize);
            _bufferSize -= sendSize;
        }
    }
```
 If you have any suggestion on how to make this work, I would love to hear it.


Thansk

**Comment by MendelMonteiro** [comment]
The Disruptor is not meant to be a shared mutable thread-safe data structure.  Its role is to facilitate message passing between multiple threads.

Events are supposed to stay in the ring buffer for as little time as possible before being consumed by the event handlers.  If an event stays in the ring buffer for a long time that is a sign that the consuming threads are not keeping up with the rate of production and that the producing threads will either have to block or drop the events to be published.

It seems to me that you want to move all the logic for maintaining the pending incremental updates to either the producing thread or the consuming thread.  If you move it all to the producing thread then the consuming thread would just receive valid snapshots and if it is moved to the consuming thread then the producing thread would simply forward all the incremental updates and snapshots.  I suspect the logic for maintaining and applying the incremental updates will be a lot easier to code if it is purely single-threaded code.
