### ISSUE TITLE
CPU Friendly IAsyncWaitStrategy?

### ISSUE THREAD

**Issue by Isolgrac** [disruptor-net/Disruptor-net#74]
We're making use of `AsyncWaitStrategy` as our event handlers need to call async code and are hitting the problem of high CPU usage, as others have before us. I see that there are a number of different WaitStrategy that have different latency / throughput / CPU balances, however there is only this one that supports async event handlers.
Is there any chance of getting a low-CPU async wait strategy, or any advice on rolling our own?

**Comment by ocoanet** [comment]
You can easily roll your own by copying the code of the `AsyncWaitStrategy` and replacing the usages of `AggressiveSpinWaitFor` by `SpinWaitFor`.

However, I think that this behavior should be provided by the library and I will add a built-in wait strategy or parameter to enable it.

Also, please note that `AggressiveSpinWaitFor` generates "soft" CPU usage: it invokes `Thread.Sleep(0)`, so it does not prevent other threads with the same priority from running. `SpinWaitFor` invokes `Thread.Sleep(1)`, so it reduces the CPU usage at the cost of additional latency.

**Comment by Isolgrac** [comment]
Thanks. Yes I had come to the same conclusion (re SpinWait) and have been trying it out. It was looking ok on Friday. I'll come back in a few days with a more definitive conclusion.

**Comment by Isolgrac** [comment]
Yeah, after a few days testing this definitely looks better 👍

**Comment by ocoanet** [comment]
Good. Please do not hesitate to ask questions or send your feedback on the async handlers.
